Repository KDT-AiVENGERS/PolarStar_AIInfra, pull requests merged in 2023-07, with the labels that each got.

#3 Feature/#2 Hugging Face + Custom Network PytorchLightning Baseline
  .DS_Store
  .gitignore
  baselines/.DS_Store
  baselines/hugging_face.ipynb
  baselines/no_transfer.ipynb
  requirements.txt
Labels: P0, ⭐️FEAT⭐️

#8 HOTFIX/#7 Requirements.txt 관련 이슈 해결
  requirements.txt
Labels: 🔥HOTFIX🔥, P0

#10 Feature/#4 Sequential Model Baseline with an example + Mecab install script + Mecab user custom dictionary setting
  .gitignore
  baselines/lang_no_transfer.ipynb
  requirements.txt
  settings/install_mecab.sh
  settings/user-nnp.csv
Labels: P0, ⭐️FEAT⭐️

#15 Feature/#11 Hugging face tokenizer, model import function, embedding vectors inference function, BERT fine-tuning function
  .gitignore
  baselines/BERT_vs_KoBERT.ipynb
  baselines/Bert_embedding.ipynb
  baselines/lang_no_transfer.ipynb
Labels: P0, ⭐️FEAT⭐️

#18 [#16]REFACTOR: 공고추천모델 Cosine similarity 계산하는 코드에 시간계산 추가
  baselines/BERT_cosine_cal.ipynb
Labels: 🍳REFACTOR🍳

#27 [#26]CHORE: fix done
  .gitignore
  baselines/Bert_embedding.ipynb
  experiment/ch/Bert_embedding_new.ipynb
  experiment/ej/Bert_embedding_new.ipynb
  experiment/ih/Bert_embedding_new.ipynb
  experiment/jh/Bert_embedding_new.ipynb
  experiment/sl/Bert_embedding_new.ipynb
  experiment/tg/Bert_embedding_new.ipynb
  experiment/tg/config.yaml
  experiment/tg/global.yaml
Labels: P0, 🎨CHORE🎨
